---
title: "meta_analysis_hf<=5_c"
output: html_document
date: "2023-07-14"
---
```{r packages, message=FALSE, warning=FALSE, echo=TRUE}
suppressPackageStartupMessages({
library("purrr")
library("metafor")
library("dplyr")
library("readxl")
library("ggplot2")
library("tidyverse")
library("readr")
library("DESeq2")

  
  
  
})
```

```{r DNAm, message=FALSE, warning=FALSE, echo=TRUE}
skeletal_muscle<-read_delim("/mnt/vol1/EWAS_BACONNED/muscle/muscle/muscle_obese/metafor_muscle_HetDf>=2.txt")
annotation<-read_csv("/mnt/vol1/annotation_latest_symbols_updated.csv")

annotation <- annotation %>%
  rename(CpG = probeID)

dnam_annot <- skeletal_muscle %>%
  inner_join(annotation, by = "CpG") %>%
  filter(!is.na(gene_symbols), gene_symbols != "")

# If gene_symbols has multiple genes separated by ; or ,
dnam_long <- dnam_annot %>%
  mutate(gene_symbols = gsub("\\s+", "", gene_symbols)) %>%
  separate_rows(gene_symbols, sep = ";|,") %>%  
  filter(gene_symbols != "")

#Make the cpg counts in gene level
dnam_gene <- dnam_long %>%
  group_by(gene = gene_symbols) %>%
  summarise(
    n_cpg        = n(),
    mean_ES_RE   = mean(ES_RE, na.rm = TRUE),
    median_ES_RE = median(ES_RE, na.rm = TRUE),
    min_pval     = min(pval_RE, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    FDR_gene = p.adjust(min_pval, method = "BH")
  )

dnam_gene %>% arrange(FDR_gene) %>% head()
dim(dnam_gene)


write.csv(
  dnam_gene,
  "/mnt/vol1/Multi-omics-skeletal-muscle-ageing/dnam_muscle_age_genes.csv",
  row.names = FALSE
)


```

```{r gtex, message=FALSE, warning=FALSE, echo=TRUE}

# GTEx skeletal muscle counts (v8)
if (! file.exists("/mnt/vol1/enrichment/ske/gene_reads_2017-06-05_v8_muscle_skeletal.gct.gz") ) {
  download.file("https://storage.googleapis.com/adult-gtex/bulk-gex/v8/rna-seq/counts-by-tissue/gene_reads_2017-06-05_v8_muscle_skeletal.gct.gz",
    destfile="/mnt/vol1/enrichment/ske/gene_reads_2017-06-05_v8_muscle_skeletal.gct.gz")
}

gtex_tisue <- read.table("/mnt/vol1/enrichment/ske/gene_reads_2017-06-05_v8_muscle_skeletal.gct.gz", header = TRUE, sep = "\t", skip = 2,check.names = FALSE)

gene_info <- gtex_tisue[, 1:2]
expr_counts <- as.matrix(gtex_tisue[, -c(1, 2)])

rownames(expr_counts) <- gene_info$Name
head(rownames(expr_counts))

expr_counts <- expr_counts[, colnames(expr_counts) != "Description"]
head(colnames(expr_counts))


# Sample attributes
if (!file.exists("/mnt/vol1/enrichment/ske/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")) {
  download.file(
    "https://storage.googleapis.com/adult-gtex/annotations/v8/metadata-files/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt",
    destfile = "/mnt/vol1/Multi-omics-skeletal-muscle-ageing/GTEx_sample_attr_file.txt"
  )
}

# Subject phenotypes
if (!file.exists("/mnt/vol1/enrichment/ske/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt")) {
  download.file(
    "https://storage.googleapis.com/adult-gtex/annotations/v8/metadata-files/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt",
    destfile = "/mnt/vol1/Multi-omics-skeletal-muscle-ageing/GTEx_subject_pheno_file.txt"
  )
}

sample_annot_gtex  <- read.delim("/mnt/vol1/Multi-omics-skeletal-muscle-ageing/GTEx_sample_attr_file.txt",  stringsAsFactors = FALSE)

subject_annot_gtex <- read.delim("/mnt/vol1/Multi-omics-skeletal-muscle-ageing/GTEx_subject_pheno_file.txt", stringsAsFactors = FALSE)


# Only Muscle - Skeletal samples
sample_muscle <- sample_annot_gtex %>%
  dplyr::filter(SMTSD == "Muscle - Skeletal")


subject_annot_gtex <- subject_annot_gtex %>%
  select(SUBJID, AGE, SEX)

# Modify the column name and the row names of sample muscle

sample_muscle <- sample_annot_gtex %>%
  filter(SMTSD == "Muscle - Skeletal") %>%
  mutate(
    # donor ID = first two chunks of SAMPID, e.g. GTEX-1117F
    SUBJID = vapply(
      strsplit(SAMPID, "-"),
      function(x) paste(x[1:2], collapse = "-"),
      character(1)
    )
  )

subject_small <- subject_annot_gtex %>%
  select(SUBJID, AGE, SEX)

pheno_muscle <- sample_muscle %>%
  left_join(subject_small, by = "SUBJID")

pheno_muscle %>%
  select(SAMPID, SUBJID, SMTSD, AGE, SEX) %>%
  head()


samples_expr <- colnames(expr_counts)
pheno_muscle2 <- pheno_muscle %>%
  filter(SAMPID %in% samples_expr)

pheno_muscle2 <- pheno_muscle2[
  match(samples_expr, pheno_muscle2$SAMPID),
]


```

```{r rnaseq, message=FALSE, warning=FALSE, echo=TRUE}

ids_expr  <- colnames(expr_counts)
ids_pheno <- pheno_muscle2$SAMPID
common_ids <- intersect(ids_expr, ids_pheno)
expr_counts_aligned  <- expr_counts[, common_ids]
#Trim any stray spaces
expr_counts_aligned <- trimws(expr_counts_aligned)

expr_counts_aligned <- matrix(
  as.numeric(expr_counts_aligned),
  nrow = nrow(expr_counts_aligned),
  ncol = ncol(expr_counts_aligned),
  dimnames = dimnames(expr_counts_aligned)
)


mode(expr_counts_aligned)

summary(as.vector(expr_counts_aligned))[1:6]
min(expr_counts_aligned, na.rm = TRUE)
any(expr_counts_aligned < 0, na.rm = TRUE)


pheno_muscle_aligned <- pheno_muscle2 %>%
  dplyr::filter(SAMPID %in% common_ids) %>%
  dplyr::arrange(match(SAMPID, common_ids))

pheno_muscle_aligned$AGE_ord <- as.numeric(factor(
  pheno_muscle_aligned$AGE,
  levels  = c("20-29","30-39","40-49","50-59","60-69","70-79"),
  ordered = TRUE
))

pheno_muscle_aligned <- pheno_muscle_aligned[!is.na(pheno_muscle_aligned$AGE_ord), ]

rownames(pheno_muscle_aligned) <- pheno_muscle_aligned$SAMPID

dds <- DESeqDataSetFromMatrix(
  countData = expr_counts_aligned,
  colData   = pheno_muscle_aligned,
  design    = ~ AGE_ord
)

head(rownames(dds))


keep<- rowSums(counts(dds)) >= 10
dds<- dds[keep, ]
dds <- DESeq(dds)
plotDispEsts(dds)

norm_counts<- counts(dds, normalized = TRUE)
glimpse(norm_counts)

vsd<- vst(dds, blind = TRUE)
vsd_mat<- assay(vsd)
vsd_mat_scaled <- t(scale(t(vsd_mat)))

ann <- as.data.frame(colData(vsd))[, c("AGE"), drop = FALSE]
ord_cols <- order(vsd$AGE_ord)

# sample–sample correlation heatmap
pheatmap::pheatmap(
  cor(assay(vsd)),
  annotation_col = ann,
  annotation_row = ann
)


# PCA by age band
DESeq2::plotPCA(vsd, intgroup = c("AGE"))


res_age <- results(dds, name = "AGE_ord", alpha = 0.05)
plotMA(res_age)

rna_gene <- as.data.frame(res_age) %>%
  rownames_to_column("gene") %>%
  transmute(
    gene,
    beta_age_rna = log2FoldChange,  
    p_rna        = pvalue,
    FDR_rna      = padj
  )

write.csv(
  rna_gene,
  "/mnt/vol1/Multi-omics-skeletal-muscle-ageing/rna_muscle_age_genes_deseq.csv",
  row.names = FALSE
)

```


```{r DNAM_RNA_MULTI, message=FALSE, warning=FALSE, echo=TRUE}

dnam_gene <- read.csv("/mnt/vol1/Multi-omics-skeletal-muscle-ageing/dnam_muscle_age_genes.csv")
rna_gene  <- read.csv("/mnt/vol1/Multi-omics-skeletal-muscle-ageing/rna_muscle_age_genes_deseq.csv")

multi_dr <- inner_join(dnam_gene, rna_gene, by = "gene")

cor(multi_dr$mean_ES_RE, multi_dr$beta_age_rna, use = "complete.obs")


```

```{r meta-analysis, message=FALSE, warning=FALSE, echo=TRUE}


```



